name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - os: ubuntu-latest
            artifacts: 'dist/packages/linux/x64/*.deb'
          - os: windows-latest
            artifacts: 'dist/packages/win/x64/*.exe'

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Building Angular
        run: yarn build
      - name: Building Electron application
        run: yarn dist
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ matrix.config.artifacts }}
          token: ${{ secrets.GITHUB_TOKEN }}
