name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Building Angular
        run: yarn build
      - name: Building Electron application
        run: yarn dist
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/packages/linux/x64/*.deb'
          token: ${{ secrets.GITHUB_TOKEN }}
